原稿
plusclass/devlog pull request #82
Opened 2021-11-18 03:17 UTC by sugi0523

2021-11-18 04:10 UTC, motoi-dev requested changes
内容は良いかと思う！修正点にあるので、修正よろしく。

次回以降、マークダウンの書き方も色々調べて試してみて下さい。
文字をboldにしたり、コードを書いたり等。

後、たかが独自で作ってくれたCustom Blockがあるから、それも次回以降活用して下さい！
どういう感じで使ってるかは他の僕らのブログを参考に。
https://github.com/plusclass/devlog
これのREADMEに使い方書いてある。

2021-11-18 04:10 UTC, motoi-dev commented on content/blog/nice-to-meet-you/index.md
> +株式会社プラスクラス、およびプラスクラス・スポーツ・インキュベーション株式会社、でエンジニアとしてインターンをしています杉原です。ハンドルネームは仲間からよく呼ばれているsugiにしました。よろしくお願いします！
それぞれ会社のリンクつけてみよう！マークダウンのリンクの付け方学ぶためにも。

2021-11-18 04:10 UTC, motoi-dev commented on content/blog/nice-to-meet-you/index.md
> +プラスクラスでやりたいこととしては、大学で機械学習を扱っているので、密かにスポーツ×AIでスポーツ業界を盛り上げるようなプロジェクトをしたいという密かな野望もあります。
いいね笑

2021-11-18 04:10 UTC, motoi-dev commented on content/blog/nice-to-meet-you/index.md
> +興味のある分野としては
ここ唐突に終わってるから、箇条書きの後に締める言葉を。
「等です。」的な。

2021-11-18 04:11 UTC, motoi-dev commented
@sugi0523 
後、そうだ、さすがに怖い、画像笑

2021-11-18 04:12 UTC, goran-nasai commented
@sugi0523 アイコンで使う画像ください！

2021-11-18 04:13 UTC, motoi-dev commented
@goran-nasai 
まだエラーで見れないな！
![Uploading image.png…]()

2021-11-18 04:13 UTC, goran-nasai commented on content/blog/nice-to-meet-you/index.md
> +株式会社プラスクラス、およびプラスクラス・スポーツ・インキュベーション株式会社、でエンジニアとしてインターンをしています杉原です。ハンドルネームは仲間からよく呼ばれているsugiにしました。よろしくお願いします！
@sugi0523 コードブロックとかも使えるからね！`sugi` みたいな！
README読んだり、マークダウンの記述の仕方勉強するように！

2021-11-18 04:15 UTC, goran-nasai commented
@motoi-dev 僕見れてますよ！`pull`してもう一度`yarn dev`で立ち上げてみてください！

2021-11-18 04:18 UTC, motoi-dev commented
@goran-nasai 
しばらくしたら表示された！なんだったんだ…さんくす！

2021-11-18 04:43 UTC, sugi0523 commented
> @sugi0523 アイコンで使う画像ください！

![bule-sugi](https://user-images.githubusercontent.com/87174879/142353195-c7350b9d-a27a-4685-9c73-f2f6e2415211.jpg)

2021-11-18 04:51 UTC, sugi0523 commented
> @sugi0523 後、そうだ、さすがに怖い、画像笑 なんか他にない？笑 これからずっと手書きで行く感じ？笑

今回だけ手書きでいこうかなと

2021-11-18 04:53 UTC, motoi-dev commented
@sugi0523 
その理由は？

2021-11-18 05:23 UTC, sugi0523 commented
@motoi-dev 
画像を探していて気に入ったからです
そんなに変ですかね？

2021-11-18 05:24 UTC, motoi-dev commented
@sugi0523 
あ、これフリー素材？

2021-11-19 04:04 UTC, motoi-dev commented
@sugi0523
フリー素材ならOKよ！自由に使っていい画像って明記されているなら。

2021-11-19 06:44 UTC, motoi-dev approved these changes
OK！

2021-11-19 08:27 UTC, merged